const ActionTypes = {
  FETCH_TODO_LOADING: 'FETCH_TODO_LOADING',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  FETCH_TODO_FAILURE: 'FETCH_TODO_FAILURE',
  POST_TODO_LOADING: 'POST_TODO_LOADING',
  POST_TODO_SUCCESS: 'POST_TODO_SUCCESS',
  POST_TODO_FAILURE: 'POST_TODO_FAILURE',
};

export default ActionTypes;
