const ActionTypes = {
  FETCH_TODO_LOADING: 'FETCH_TODO_LOADING',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  FETCH_TODO_FAILURE: 'FETCH_TODO_FAILURE',
  POST_TODO_LOADING: 'POST_TODO_LOADING',
  POST_TODO_SUCCESS: 'POST_TODO_SUCCESS',
  POST_TODO_FAILURE: 'POST_TODO_FAILURE',
  DELETE_TODO_LOADING: 'DELETE_TODO_LOADING',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',
  UPDATE_TODO_LOADING: 'UPDATE_TODO_LOADING',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
  GET_TODO_LOADING: 'GET_TODO_LOADING',
  GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
  GET_TODO_FAILURE: 'GET_TODO_FAILURE',
};

export default ActionTypes;
